# Docker compose for the development environment
services:
    # Base image for our devcontainer
    devcontainer:
      labels:
        com.webdev.category: "devcontainer"
      build: 
        context: .
        dockerfile: Dockerfile
      volumes:
        - ..:/var/www/html:cached
      command: sleep infinity
      networks:
        - webdev-network

    # MySql Server
    # For more infos check: https://hub.docker.com/_/mysql/
    mysql:
      labels:
        com.webdev.category: "database"
      image: mysql:8.4
      container_name: "mysql"
      networks:
        - webdev-network
      ports:
        # make this port public so it can also accessed via HeidiSQL or similar tools
        - 3306:3306
      environment:
        # mysql root password
        - MYSQL_ROOT_PASSWORD=webdev
        # create this database by default
        - MYSQL_DATABASE=webdev

    # Mailpit (can fetch all outgoing mails and show them via webinterface)
    # For more infos check: https://hub.docker.com/r/axllent/mailpit
    mailpit:
      labels:
        com.webdev.category: "mail"
      image: axllent/mailpit:latest
      container_name: "mailpit"
      networks:
        - webdev-network
      ports:
        # make this port public for the webinterface
        - 8025:8025
        # port for incoming mails
        - 1025:1025

    # Redis Server
    # For more infos check: https://hub.docker.com/_/redis
    redis:
      labels:
        com.webdev.category: "cache"
      image: redis:latest
      networks:
        - webdev-network
      container_name: "redis"
      ports:
        - 6379:6379

    # PhpMyAdmin
    # For more infos check: https://hub.docker.com/_/phpmyadmin
    phpmyadmin:
      labels:
        com.webdev.category: "tools"
      image: phpmyadmin/phpmyadmin:fpm-alpine
      container_name: "pma"
      restart: always
      networks:
        - webdev-network
      environment:
        PMA_HOST: "localhost"
        PMA_PORT: 3306
        PMA_USER: "root"
        PMA_PASSWORD: "webdev"
        UPLOAD_LIMIT: 2048M
        PMA_PMADB: "pma"
      ports:
        - "8081:80"
      volumes:
        - /tmp/apache2/logs:/var/log/apache2

    # PhpCacheAdmin
    # For more infos check: https://hub.docker.com/r/robinn/phpcacheadmin
    phpcacheadmin:
      labels:
        com.webdev.category: "tools"
      image: robinn/phpcacheadmin
      container_name: "phpcacheadmin"
      networks:
        - webdev-network
      ports:
        - "8082:80"
      environment:
        - PCA_REDIS_0_HOST=redis
        - PCA_REDIS_0_PORT=6379
      volumes:
        - /tmp/apache2/logs:/var/log/apache2

networks:
  webdev-network:
    driver: bridge